name: build
on: workflow_dispatch
jobs:
  build:
    name: Build the image
    runs-on: ubuntu-20.04
    steps:
    - name: "Check out repo"
      uses: actions/checkout@v2
    - name: "Login to GitHub Container Registry"
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: "Build egf-notebook Docker image"
      run: |
        docker build . \
          --tag ghcr.io/edinburgh-genome-foundry/egf_docker_jupyter/egf-notebook:latest \
          --tag ghcr.io/edinburgh-genome-foundry/egf_docker_jupyter/egf-notebook:v0.2.0
    - name: "Release Docker image"
      run: |
        docker push ghcr.io/edinburgh-genome-foundry/egf_docker_jupyter/egf-notebook:latest
        docker push ghcr.io/edinburgh-genome-foundry/egf_docker_jupyter/egf-notebook:v0.2.0
