name: build
on: workflow_dispatch
jobs:
  build:
    name: Build the image
    runs-on: ubuntu-18.04
    steps:
    - name: "Build egf-notebook Docker image"
      uses: actions/checkout@v2
      run: |
        docker build . \
          --tag ghcr.io/${{ github.repository }}:v0.1.0
    - name: "Login to GitHub container registry"
      run: |
        echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io \
          --username ${{ github.repository_owner }} \
          --password-stdin
    - name: "Release Docker image"
      run: |
        docker push ghcr.io/${{ github.repository }}:v0.1.0
