name: build
on: workflow_dispatch
jobs:
  build:
    name: Build the image
    runs-on: ubuntu-18.04
    steps:
    - name: "Check out repo"
      uses: actions/checkout@v2

    - name: "Build egf-notebook Docker image"
      run: |
        docker build . \
          --tag ghcr.io/edinburgh-genome-foundry/egf_docker_jupyter/egf-notebook:v0.1.0
    - name: "Login to GitHub container registry"
      run: |
        echo ${{ secrets.CR_PAT }} | docker login ghcr.io \
          --username ${{ github.repository_owner }} \
          --password-stdin
    - name: "Release Docker image"
      run: |
        docker push ghcr.io/edinburgh-genome-foundry/egf_docker_jupyter/egf-notebook:v0.1.0
